name:               "FSAS test"
description:        "test page for FSAS"

url:                ""
author:             ""
email:              ""
gravatar_hash:      ""
twitter:            ""
email:              ""
github:             ""
linkedin:           ""

disqus_shortname:   ""

background:         "/resources/w-5273.jpg"

paginate:           2
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
