name:               "Ben Batorsky"
description:        "Data Scientist and nice guy"

url:                ""
author:             "bpben"
email:              "yksrotab@gmail.com"
gravatar_hash:      ""
twitter:            "bpben2"
email:              "yksrotab@gmail.com"
github:             "bpben"
pinterest:          ""
linkedin:           "https://www.linkedin.com/in/benjamin-batorsky-1b883b27"
facebook:           ""

disqus_shortname:   ""

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate